name: Code Review Checks

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run lint
